"""Custom syrupy serializers for HTML snapshot testing."""

import re
from typing import Any

from syrupy.extensions.amber import AmberSnapshotExtension
from syrupy.types import SerializableData


class NormalisedHTMLSerializer(AmberSnapshotExtension):
    """
    Custom serializer that normalises dynamic content in HTML output.

    Normalises only truly dynamic content:
    - Library version comments (changes between releases)
    - Pytest tmp paths (varies per test run)

    Note: Timestamps, UUIDs, message IDs, token counts etc. come from the
    source JSONL test fixtures which are committed and static - no normalisation needed.
    """

    @classmethod
    def serialize(cls, data: SerializableData, **kwargs: Any) -> str:
        if isinstance(data, str):
            normalised = cls._normalise_html(data)
            return normalised
        return str(super().serialize(data, **kwargs))

    @classmethod
    def _normalise_html(cls, html: str) -> str:
        """Apply normalisation rules to HTML content."""
        # Library version (changes between releases)
        # <!-- Generated by claude-code-log v0.8.0 --> -> <!-- Generated by claude-code-log v[VERSION] -->
        html = re.sub(
            r"<!-- Generated by claude-code-log v[\d.]+(-\w+)? -->",
            "<!-- Generated by claude-code-log v[VERSION] -->",
            html,
        )

        # Pytest tmp paths (from tmp_path fixture)
        # /tmp/pytest-123/test_foo0/ -> /[TMP_PATH]/
        # /private/var/folders/.../pytest-123/... -> /[TMP_PATH]/
        html = re.sub(
            r"(/private)?(/var/folders/[^/]+/[^/]+/[^/]+/)?/tmp/pytest-[^\s\"'<>]+",
            "/[TMP_PATH]",
            html,
        )

        # Last modified timestamps in project index (timezone-dependent)
        # 🕒 2023-11-14 23:15:00 -> 🕒 [LAST_MODIFIED]
        # These come from datetime.fromtimestamp() which uses local timezone
        html = re.sub(
            r"🕒 \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}</div>",
            "🕒 [LAST_MODIFIED]</div>",
            html,
        )

        return html
