"use client";

import { useEffect, useState, useRef } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { Suspense } from "react";

interface ProjectReport {
  name: string;
  path: string;
  sessions: number;
  events: number;
  inputTokens: number;
  outputTokens: number;
  cacheCreationTokens: number;
  cacheReadTokens: number;
  totalTokens: number;
  estimatedCostUsd: number;
  users: string[];
  lastActivity: string;
}

interface ReportData {
  from: string;
  to: string;
  totalSessions: number;
  totalTokens: number;
  totalEvents: number;
  estimatedCostUsd: number;
  projects: ProjectReport[];
}

function fmt(n: number) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function daysAgo(n: number) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

function exportHTML(data: ReportData, from: string, to: string) {
  const rows = data.projects
    .map(
      (p) => `
    <tr>
      <td><strong>${p.name}</strong><br><small style="color:#888">${p.path}</small></td>
      <td style="text-align:right">${p.sessions}</td>
      <td style="text-align:right">${p.events}</td>
      <td style="text-align:right">${fmt(p.totalTokens)}</td>
      <td style="text-align:right">$${p.estimatedCostUsd.toFixed(4)}</td>
      <td>${p.users.join(", ") || "—"}</td>
    </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="utf-8">
<title>Claude Reporter - Report ${from} → ${to}</title>
<style>
  body { font-family: -apple-system, sans-serif; max-width: 960px; margin: 40px auto; padding: 0 20px; color: #e2e8f0; background: #0a0a0a; }
  h1 { color: #818cf8; } h2 { color: #94a3b8; font-size: 1rem; font-weight: 400; margin-top: 0; }
  .cards { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 24px 0; }
  .card { background: #1a1a2e; border: 1px solid #2d2d3d; border-radius: 8px; padding: 16px; }
  .card-val { font-size: 2rem; font-weight: 700; color: #818cf8; }
  .card-label { font-size: 0.75rem; color: #64748b; }
  table { width: 100%; border-collapse: collapse; margin-top: 24px; }
  th { text-align: left; padding: 8px 12px; color: #64748b; font-size: 0.8rem; border-bottom: 1px solid #2d2d3d; }
  td { padding: 8px 12px; border-bottom: 1px solid #1e1e2e; font-size: 0.85rem; }
  tr:hover td { background: #1a1a2e; }
</style>
</head>
<body>
<h1>◆ Claude Reporter</h1>
<h2>Report: ${from} → ${to}</h2>
<div class="cards">
  <div class="card"><div class="card-label">Sessions</div><div class="card-val">${data.totalSessions}</div></div>
  <div class="card"><div class="card-label">Total Tokens</div><div class="card-val">${fmt(data.totalTokens)}</div></div>
  <div class="card"><div class="card-label">Events</div><div class="card-val">${fmt(data.totalEvents)}</div></div>
  <div class="card"><div class="card-label">Est. Cost</div><div class="card-val">$${data.estimatedCostUsd.toFixed(2)}</div></div>
</div>
<table>
  <thead><tr>
    <th>Project</th><th style="text-align:right">Sessions</th><th style="text-align:right">Events</th>
    <th style="text-align:right">Tokens</th><th style="text-align:right">Cost</th><th>Users</th>
  </tr></thead>
  <tbody>${rows}</tbody>
</table>
<p style="color:#64748b;font-size:0.75rem;margin-top:32px">Generated by Claude Reporter · ${new Date().toLocaleString()}</p>
</body></html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `claude-report-${from}-${to}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

function ReportPageInner() {
  const searchParams = useSearchParams();
  const defaultUserId = searchParams.get("userId") ?? "";

  const [from, setFrom] = useState(daysAgo(30));
  const [to, setTo] = useState(today());
  const [userId, setUserId] = useState(defaultUserId);
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [report, setReport] = useState<ReportData | null>(null);
  const [visibleProjects, setVisibleProjects] = useState<number>(0);
  const [currentProject, setCurrentProject] = useState<string>("");
  const timerRef = useRef<ReturnType<typeof setTimeout>[]>([]);

  // Read UUID from localStorage on mount
  useEffect(() => {
    if (!defaultUserId) {
      const stored = localStorage.getItem("claude-reporter-uuid");
      if (stored) setUserId(stored);
    }
  }, [defaultUserId]);

  async function generate() {
    setStatus("loading");
    setReport(null);
    setVisibleProjects(0);
    timerRef.current.forEach(clearTimeout);
    timerRef.current = [];

    try {
      const qs = new URLSearchParams({ from, to, ...(userId ? { userId } : {}) });
      const res = await fetch(`/api/report?${qs}`);
      const data: ReportData = await res.json();
      setReport(data);
      setStatus("done");

      // Animate projects appearing one by one
      setCurrentProject(data.projects[0]?.name ?? "");
      data.projects.forEach((p, i) => {
        const t1 = setTimeout(() => {
          setCurrentProject(p.name);
        }, i * 300);
        const t2 = setTimeout(() => {
          setVisibleProjects(i + 1);
        }, i * 300 + 150);
        timerRef.current.push(t1, t2);
      });
    } catch {
      setStatus("error");
    }
  }

  const inputStyle: React.CSSProperties = {
    background: "var(--bg)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "0.4rem 0.6rem",
    color: "var(--text)",
    fontSize: "0.85rem",
    outline: "none",
  };

  const btnStyle = (active?: boolean): React.CSSProperties => ({
    background: active ? "var(--accent)" : "var(--surface)",
    color: active ? "#fff" : "var(--text-muted)",
    border: "1px solid var(--border)",
    borderRadius: 5,
    padding: "2px 8px",
    fontSize: "0.72rem",
    cursor: "pointer",
  });

  return (
    <div style={{ maxWidth: 900, margin: "0 auto" }}>
      {/* Header */}
      <div style={{ display: "flex", alignItems: "center", gap: "1rem", marginBottom: "1.5rem" }}>
        <div>
          <h1 style={{ fontSize: "1.1rem", fontWeight: 700, margin: 0 }}>Export Report</h1>
          <p style={{ color: "var(--text-muted)", fontSize: "0.8rem", margin: "2px 0 0" }}>
            Tổng hợp dữ liệu theo dự án trong khoảng thời gian
          </p>
        </div>
        <Link href="/" style={{ marginLeft: "auto", color: "var(--text-muted)", fontSize: "0.8rem", textDecoration: "none" }}>
          ← Trang chủ
        </Link>
      </div>

      {/* Controls */}
      <div className="card" style={{ marginBottom: "1rem" }}>
        <div style={{ display: "flex", gap: "1rem", flexWrap: "wrap", alignItems: "flex-end" }}>
          <div>
            <div style={{ color: "var(--text-muted)", fontSize: "0.72rem", marginBottom: 4 }}>Từ ngày</div>
            <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} style={inputStyle} />
          </div>
          <div>
            <div style={{ color: "var(--text-muted)", fontSize: "0.72rem", marginBottom: 4 }}>Đến ngày</div>
            <input type="date" value={to} onChange={(e) => setTo(e.target.value)} style={inputStyle} />
          </div>

          {/* Quick range buttons */}
          <div>
            <div style={{ color: "var(--text-muted)", fontSize: "0.72rem", marginBottom: 4 }}>Nhanh</div>
            <div style={{ display: "flex", gap: "0.3rem" }}>
              {[
                { label: "7d", days: 7 },
                { label: "30d", days: 30 },
                { label: "90d", days: 90 },
              ].map((r) => (
                <button
                  key={r.label}
                  onClick={() => { setFrom(daysAgo(r.days)); setTo(today()); }}
                  style={btnStyle()}
                >
                  {r.label}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={generate}
            disabled={status === "loading"}
            style={{
              background: status === "loading" ? "var(--surface)" : "var(--accent)",
              color: "#fff",
              border: "none",
              borderRadius: 6,
              padding: "0.45rem 1.25rem",
              fontWeight: 600,
              fontSize: "0.85rem",
              cursor: status === "loading" ? "default" : "pointer",
              opacity: status === "loading" ? 0.7 : 1,
            }}
          >
            {status === "loading" ? "Đang tạo…" : "Generate Report"}
          </button>
        </div>
      </div>

      {/* Loading state — project by project */}
      {status === "loading" && (
        <div className="card" style={{ padding: "2rem", textAlign: "center" }}>
          <div style={{ color: "var(--accent)", fontSize: "0.9rem", marginBottom: 8 }}>
            ⏳ Đang phân tích dữ liệu…
          </div>
          {currentProject && (
            <div style={{ color: "var(--text-muted)", fontSize: "0.8rem" }}>
              Đang xử lý project: <strong style={{ color: "var(--text)" }}>{currentProject}</strong>
            </div>
          )}
        </div>
      )}

      {/* Error */}
      {status === "error" && (
        <div className="card" style={{ color: "var(--red)", textAlign: "center" }}>
          Có lỗi xảy ra. Thử lại nhé.
        </div>
      )}

      {/* Report output */}
      {status === "done" && report && (
        <>
          {/* Summary cards */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
              gap: "0.75rem",
              marginBottom: "1rem",
            }}
          >
            {[
              { label: "Sessions", value: report.totalSessions, color: "var(--accent)" },
              { label: "Total Events", value: fmt(report.totalEvents), color: "var(--green)" },
              { label: "Total Tokens", value: fmt(report.totalTokens), color: "var(--yellow)" },
              { label: "Est. Cost", value: `$${report.estimatedCostUsd.toFixed(2)}`, color: "#f97316" },
              { label: "Projects", value: report.projects.length, color: "#a78bfa" },
            ].map((c) => (
              <div key={c.label} className="card" style={{ padding: "0.75rem 1rem" }}>
                <div style={{ color: "var(--text-muted)", fontSize: "0.7rem" }}>{c.label}</div>
                <div style={{ color: c.color, fontSize: "1.5rem", fontWeight: 700, lineHeight: 1.2 }}>{c.value}</div>
              </div>
            ))}
          </div>

          {/* Project cards — animated */}
          <div style={{ marginBottom: "1rem" }}>
            <div style={{ fontWeight: 600, fontSize: "0.9rem", marginBottom: "0.75rem" }}>
              Breakdown theo dự án
            </div>
            {report.projects.map((p, i) => (
              <div
                key={p.path || p.name}
                className="card"
                style={{
                  marginBottom: "0.6rem",
                  opacity: i < visibleProjects ? 1 : 0,
                  transform: i < visibleProjects ? "translateY(0)" : "translateY(8px)",
                  transition: "opacity 0.25s ease, transform 0.25s ease",
                  padding: "0.9rem 1rem",
                }}
              >
                <div style={{ display: "flex", alignItems: "flex-start", gap: "1rem", flexWrap: "wrap" }}>
                  {/* Project name */}
                  <div style={{ flex: "0 0 auto", minWidth: 180 }}>
                    <div style={{ fontWeight: 600, fontSize: "0.9rem" }}>{p.name}</div>
                    <div
                      style={{
                        color: "var(--text-muted)",
                        fontSize: "0.68rem",
                        fontFamily: "monospace",
                        marginTop: 2,
                        maxWidth: 260,
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                        whiteSpace: "nowrap",
                      }}
                    >
                      {p.path || "—"}
                    </div>
                    {p.users.length > 0 && (
                      <div style={{ color: "var(--text-muted)", fontSize: "0.68rem", marginTop: 4 }}>
                        👤 {p.users.join(", ")}
                      </div>
                    )}
                  </div>

                  {/* Metrics */}
                  <div style={{ display: "flex", gap: "1.25rem", flexWrap: "wrap", flex: 1 }}>
                    {[
                      { label: "Sessions", value: p.sessions, color: "var(--accent)" },
                      { label: "Events", value: fmt(p.events), color: "var(--green)" },
                      { label: "Tokens", value: fmt(p.totalTokens), color: "var(--yellow)" },
                      { label: "Cost", value: `$${p.estimatedCostUsd.toFixed(4)}`, color: "#f97316" },
                    ].map((m) => (
                      <div key={m.label}>
                        <div style={{ color: "var(--text-muted)", fontSize: "0.68rem" }}>{m.label}</div>
                        <div style={{ color: m.color, fontWeight: 700, fontSize: "0.95rem" }}>{m.value}</div>
                      </div>
                    ))}
                  </div>

                  {/* Token bar */}
                  <div style={{ width: 140, flexShrink: 0 }}>
                    <div style={{ color: "var(--text-muted)", fontSize: "0.68rem", marginBottom: 4 }}>Token split</div>
                    {[
                      { label: "In", val: p.inputTokens, color: "#6366f1" },
                      { label: "Out", val: p.outputTokens, color: "#22c55e" },
                      { label: "Cache", val: p.cacheReadTokens + p.cacheCreationTokens, color: "#eab308" },
                    ].map((b) => {
                      const pct = p.totalTokens > 0 ? Math.round((b.val / p.totalTokens) * 100) : 0;
                      return (
                        <div key={b.label} style={{ display: "flex", alignItems: "center", gap: 4, marginBottom: 3 }}>
                          <div style={{ width: 24, fontSize: "0.6rem", color: "var(--text-muted)" }}>{b.label}</div>
                          <div style={{ flex: 1, height: 5, background: "var(--border)", borderRadius: 2, overflow: "hidden" }}>
                            <div style={{ width: `${pct}%`, height: "100%", background: b.color, borderRadius: 2 }} />
                          </div>
                          <div style={{ width: 28, fontSize: "0.6rem", color: "var(--text-muted)", textAlign: "right" }}>{pct}%</div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            ))}

            {report.projects.length === 0 && (
              <div className="card" style={{ textAlign: "center", color: "var(--text-muted)", padding: "2rem" }}>
                Không có dữ liệu trong khoảng thời gian này.
              </div>
            )}
          </div>

          {/* Export button */}
          {report.projects.length > 0 && (
            <div style={{ textAlign: "center", marginTop: "1.5rem" }}>
              <button
                onClick={() => exportHTML(report, from, to)}
                style={{
                  background: "var(--accent)",
                  color: "#fff",
                  border: "none",
                  borderRadius: 6,
                  padding: "0.5rem 1.5rem",
                  fontWeight: 600,
                  fontSize: "0.85rem",
                  cursor: "pointer",
                }}
              >
                ↓ Tải HTML Report
              </button>
            </div>
          )}
        </>
      )}
    </div>
  );
}

export default function ReportPage() {
  return (
    <Suspense>
      <ReportPageInner />
    </Suspense>
  );
}
